version: "3"
services:
  os-ubuntu:
    container_name: os-ubuntu
    build: ./build/
    restart: on-failure
    tty: true
    platform: linux/amd64
    volumes:
      - "/tmp/sweb/:/tmp/sweb/"
      - "./src/:/tmp/src/"
